### PR TITLE
Jellyfin port

### PR DESCRIPTION
**Pull request by hawken93**
This is how far I came, but it still doesn't compile. Any help figuring out the remaining errors is welcome!

### CODE REVIEW

**Comment by hawken93** [comment]
@cvium has now helped me out and while I haven't tested it myself, I believe it should compile now. :)

**Comment by cvium** [comment]
@hawken93 I think I rushed the fix too much. Now that I've given it some thought, I think we should just revert to https://github.com/jellyfin/jellyfin-plugin-trakt/commit/8e47b95987b8b00f2658783f725faf43e2371a58 and any compatibility issues will be gone (the ones we didn't cause).

**Comment by hawken93** [comment]
@cvium sorry about the discussion on matrix, I had in mind another plugin port when I talked with you then. This one seemed like a harder fix so I agree with you completely here

**Comment by hawken93** [comment]
retiring this in favor of @cvium s PR :)

**Pull request closed without merging**
